# SEO settings
title: megadaptor
description: "blog"
keywords: "hacking, ctf, writeups"
url: https://megadaptor.github.io
baseurl: null

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# Social networking, etc
repo: http://github.com/megadaptor/megadaptor.github.io

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: page
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            comments: true

# asciinema defaults
asciicast:
    cols: "115"
    rows: "25"
    speed: "3.0"
    theme: "monokai"

# Search settings
tipue_search:
  include:
    pages: false
#    collections: [apps]
  exclude:
    files: [index.html, 
            pages/search.md, 
            search.md]


# Build settings
permalink   : /:year/:title/
markdown    : kramdown

paginate: 4
paginate_path: "/page/:num/"
comments: true

destination: _site

# Author settings
author:
  name     : megadaptor
  bio      : "i love tinkering with everything."
  thumb    : /images/author.jpg
  url      : https://megadaptor.github.io
  github   : http://github.com/megadaptor
  linkedin : https://linkedin.com/in/tasneem-johan-77866a200/
# social settings
og_locale: "en_US"

plugins:
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: [".git", "README.md", "LICENSE.md", "_site", "_drafts", "vendor"]
